/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as ParkingRouteImport } from './routes/parking'
import { Route as DepartureRouteImport } from './routes/departure'
import { Route as ArrivalRouteImport } from './routes/arrival'
import { Route as AirportGuideRouteImport } from './routes/airport-guide'
import { Route as IndexRouteImport } from './routes/index'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingRoute = ParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartureRoute = DepartureRouteImport.update({
  id: '/departure',
  path: '/departure',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalRoute = ArrivalRouteImport.update({
  id: '/arrival',
  path: '/arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportGuideRoute = AirportGuideRouteImport.update({
  id: '/airport-guide',
  path: '/airport-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airport-guide': typeof AirportGuideRoute
  '/arrival': typeof ArrivalRoute
  '/departure': typeof DepartureRoute
  '/parking': typeof ParkingRoute
  '/transfer': typeof TransferRoute
  '/transport': typeof TransportRoute
  '/venues': typeof VenuesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airport-guide': typeof AirportGuideRoute
  '/arrival': typeof ArrivalRoute
  '/departure': typeof DepartureRoute
  '/parking': typeof ParkingRoute
  '/transfer': typeof TransferRoute
  '/transport': typeof TransportRoute
  '/venues': typeof VenuesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airport-guide': typeof AirportGuideRoute
  '/arrival': typeof ArrivalRoute
  '/departure': typeof DepartureRoute
  '/parking': typeof ParkingRoute
  '/transfer': typeof TransferRoute
  '/transport': typeof TransportRoute
  '/venues': typeof VenuesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/airport-guide'
    | '/arrival'
    | '/departure'
    | '/parking'
    | '/transfer'
    | '/transport'
    | '/venues'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/airport-guide'
    | '/arrival'
    | '/departure'
    | '/parking'
    | '/transfer'
    | '/transport'
    | '/venues'
  id:
    | '__root__'
    | '/'
    | '/airport-guide'
    | '/arrival'
    | '/departure'
    | '/parking'
    | '/transfer'
    | '/transport'
    | '/venues'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirportGuideRoute: typeof AirportGuideRoute
  ArrivalRoute: typeof ArrivalRoute
  DepartureRoute: typeof DepartureRoute
  ParkingRoute: typeof ParkingRoute
  TransferRoute: typeof TransferRoute
  TransportRoute: typeof TransportRoute
  VenuesRoute: typeof VenuesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking': {
      id: '/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof ParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departure': {
      id: '/departure'
      path: '/departure'
      fullPath: '/departure'
      preLoaderRoute: typeof DepartureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrival': {
      id: '/arrival'
      path: '/arrival'
      fullPath: '/arrival'
      preLoaderRoute: typeof ArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airport-guide': {
      id: '/airport-guide'
      path: '/airport-guide'
      fullPath: '/airport-guide'
      preLoaderRoute: typeof AirportGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirportGuideRoute: AirportGuideRoute,
  ArrivalRoute: ArrivalRoute,
  DepartureRoute: DepartureRoute,
  ParkingRoute: ParkingRoute,
  TransferRoute: TransferRoute,
  TransportRoute: TransportRoute,
  VenuesRoute: VenuesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
